---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
        - name: ombi-container
          image: linuxserver/ombi
---
apiVersion: v1
kind: Service
metadata:
  name: ombi-service
spec:
  ports:
    - name: http
      targetPort: 3579
      port: 80
  selector:
    app: ombi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: kube.local
      http:
        paths:
          - path: /whoami
            backend:
              serviceName: whoami-service
              servicePort: http
