#!/usr/bin/env python3
#TODO: mount shared drive - do this later when necessary
import sys
import os
import subprocess
import urllib.request

def set_ip:
    file_name = "/etc/netplan/50-cloud-init.yaml"
    url = "https://raw.githubusercontent.com/colonelpopcorn/home-server/master/hosts/single-docker-host/50-cloud-init.yaml"
    urllib.request.urlretrieve(url, file_name)
    set_ip_script = """
    netplan apply
    """
    subprocess.call(['sh', '-c', set_ip_script])

def install_docker:
    set_up_repo_script = """
    sudo apt-get update
    sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io
    sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    """
    subprocess.call(['sh', '-c', set_up_repo_script])
        