# Portainer agent
version: "3"
services:
  agent:
    image: portainer/agent
    restart: always
    container_name: portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:9001