version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "28090:8090"
    volumes:
      - ${DOCKER_DIR}/pocketbase:/pb_data