---
- hosts: homeserver
  remote_user: jonathan
  become: yes
  become_method: sudo
  tasks:
    - name: Install usbmount
      apt:
        name: usbmount
        state: present
        update_cache: yes
