---
- hosts: homeserver
  remote_user: jonathan
  become: yes
  become_method: sudo
  roles:
    - mongrelion.docker
  tasks:

    - name: Copy shell script
      copy:
        src: "{{ playbook_dir }}/docker-up.sh"
        dest: "{{ ansible_env.HOME }}/docker-up.sh"
        mode: 0755

    - name: Run our docker container
      script: "{{ ansible_env.HOME }}/docker-up.sh"
