---
- hosts: homeserver
  remote_user: jonathan
  become: yes
  become_method: sudo
  vars:
    vagrant_latest_num: 1.9.1
    vagrant_latest: vagrant_1.9.1_x86_64.deb
  tasks:
    
    - name: Install virtualbox and extension pack
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        with_items:
          - virtualbox
          - virtualbox-ext-pack

    - name: Get vagrant latest
      get_url:
        url: "https://releases.hashicorp.com/vagrant/{{ vagrant_latest_num }}/{{ vagrant_latest }}"
        dest: "{{ ansible_env.HOME }}"

    - name: Install vagrant latest
      apt:
        deb: "{{ ansible_env.HOME }}/{{ vagrant_latest }}"

    - name: Copy vagrant file to box
      copy:
        src: "{{ playbook_dir }}/Vagrantfile"
        dest: {{ ansible_env.HOME }}/Vagrantfile

    - name: Run vagrant up
      shell:
        cmd: vagrant up
        chdir: "{{ ansible_env.HOME }}"
