version: "2"
services:
  #region Watchtower - Automatic Update of Containers/Apps
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
  #endregion
networks:
  default:
    driver: bridge
