version: '3'
services:
  handbrake:
    container_name: handbrake
    depends_on:
      - handbrake-init
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    environment:
      - USER_ID=1000
      - GROUP_ID=100
      - TZ=America/New_York
      - AUTOMATED_CONVERSION_PRESET=General/HQ 1080p30 Surround
      - AUTOMATED_CONVERSION_PRESET_2=General/HQ 720p30 Surround
      - AUTOMATED_CONVERSION_PRESET_3=General/HQ 1080p30 Surround
      - AUTOMATED_CONVERSION_PRESET_4=General/HQ 720p30 Surround
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_2=SAME_AS_SRC
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_3=SAME_AS_SRC
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_4=SAME_AS_SRC
    volumes:
      - "${DOCKER_DIR}/handbrake_appdata:/config:rw"
      - "${DOCKER_DIR}/HandBrake/input:/storage:ro"
      - "${DOCKER_DIR}/HandBrake/watch:/watch:rw"
      - "${DOCKER_DIR}/HandBrake/watch2:/watch2:rw"
      - "${DOCKER_DIR}/HandBrake/watch3:/watch3:rw"
      - "${DOCKER_DIR}/HandBrake/watch4:/watch4:rw"
      - "${DOCKER_DIR}/HandBrake/output:/output:rw"
      - "${DOCKER_DIR}/gossa:/ingest:rw"
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
  handbrake-init:
    container_name: handbrake-init
    restart: 'no'
    image: alpine
    volumes:
      - "${DOCKER_DIR}/handbrake_appdata:/config:rw"
    command: |
      sh -c "echo > /config/post_conversion.sh << EOF
      #!/bin/sh
      #
      # This is an example of a post-conversion hook.  This script is always invoked
      # with /bin/sh (shebang ignored).
      #
      # The first parameter is the conversion status.  A value of 0 indicates that
      # the video has been converted successfully.  Else, conversion failed.
      #
      # The second parameter is the full path to the converted video (the output).
      #
      # The third parameter is the full path to the source file.
      #
      # The fourth argument is the name of the HandBrake preset used to convert the
      # video.
      #

      CONVERSION_STATUS=$1
      CONVERTED_FILE="$2"
      SOURCE_FILE="$3"
      PRESET="$4"

      echo "post-conversion: Status = $CONVERSION_STATUS"
      echo "post-conversion: Output File = $CONVERTED_FILE"
      echo "post-conversion: Source File = $SOURCE_FILE"
      echo "post-conversion: Preset = $PRESET"

      if [ "$CONVERSION_STATUS" -eq 0 ]; then
          # Successful conversion.
          rm -rf $(dirname "$SOURCE_FILE")
          if [ "$SOURCE_FILE" == *"watch4"* ] || [ "$SOURCE_FILE" == *"watch3"*]; then
            mv $(dirname "$CONVERTED_FILE") /ingest/Televison
          else
            mv $(dirname "$CONVERTED_FILE") /ingest/Movies
          fi
      else
          # Failed conversion.

          # TODO: Do something useful.
          :
      fi

