version: '2'
services:
  adminer:
    image: adminer
    networks:
      - database
    container_name: adminer
    restart: always
    ports:
      - 9090:8080
networks:
  database:
    external:
      name: database