version: '2'
services:
  adminer:
    image: adminer
    container_name: adminer
    networks:
      - database
    restart: always
    ports:
      - 9090:8080
  postgresql:
    image: postgres:14-alpine
    container_name: postgresql
    networks:
      - database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DOCKER_DIR}/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  database:
    external:
      name: database