version: '2'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ${DOCKER_DIR}/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
networks:
  database:
    external:
      name: database