version: '2'
services:
 transmission:
    container_name: transmission-ovpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/transmission-vpn:/data
      - ${DOCKER_DIR}/shared:/shared
      - ${DOCKER_DIR}/Downloads:/data/watch
      - ${DOCKER_DIR}/Downloads/completed:/data/completed
      - ${DOCKER_DIR}/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${TRANSMISSION_VPN_USERNAME}
      - OPENVPN_PASSWORD=${TRANSMISSION_VPN_PASSWORD}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - LOCAL_NETWORK=${LOCAL_NETWORK}