Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "10.0.1.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      "storageattach", :id,
      "--storagectl", "IDE",
      "--port", "0", "--device", "1",
      "--type", "dvddrive",
      "--medium", "host:F:",
      "--passthrough", "on"
    ]
  end
  # provisioner = Vagrant::Util::Platform.windows? ? :ansible_local : :ansible
  # config.vm.provision provisioner do |ansible|
  #   ansible.limit = "all"
  #   ansible.become = true
  #   ansible.playbook = "bootstrap.yml"
  #   ansible.galaxy_role_file = "requirements.yml"
  #   ansible.install_mode = "pip"
  # end
  config.trigger.before :destroy do |trigger|
    trigger.info = "Removing DVD drive..."
  end
end
