# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["storageattach", :id,
                  "--storagectl", "IDE",
                  "--port", "0", "--device", "1",
                  "--type", "dvddrive",
                  "--medium", "emptydrive"]
  end
  config.vm.provision :ansible do |ansible|
    ansible.limit = "all"
    ansible.become = true
    ansible.playbook = "bootstrap.yml"
  end
end
