version: "3"
services:
  # region Guacamole - RDP client for accessing compute resources inside the network
  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
    links:
      - guacd
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.entrypoints=https"
      - "traefik.http.routers.guacamole.tls=true"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.${DOMAIN_NAME}`)"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=guacdb
      - MYSQL_DATABASE=guacamole
      - MYSQL_PORT=3306
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - GUACAMOLE_HOME=/guacamole
      - EXTENSIONS=auth-totp
    image: guacamole/guacamole
    volumes:
      - ${DOCKER_DIR}/guacamole:/guacamole
    restart: always
  guacd:
    hostname: guacd
    container_name: guacd
    image: guacamole/guacd
    networks:
      - default
    restart: always
  guacdb:
    image: mariadb:latest
    container_name: guacdb
    restart: always
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=guacamole
    volumes:
      - ${DOCKER_DIR}/guacamole/mariadb:/var/lib/mysql
#endregion
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
