version: '3'
services:
  guacamole:
    depends_on:
      - guacd
    links:
      - guacd
    labels:
      - "traefik.enable=true"
      - "traefik.gittea.backend=guacamole"
      - "traefik.gittea.frontend.rule=Host:guacamole.${DOMAIN_NAME}"
      - "traefik.gittea.port=8080"
      - "traefik.docker.network=traefik_proxy"
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - GUACAMOLE_HOME=${DOCKER_DIR}/guacamole
    image: guacamole/guacamole
    restart: always
  guacd:
    hostname: guacd
    image: guacamole/guacd
    restart: always
