version: "2"
services:
  #region Guacamole - RDP client for accessing compute resources inside the network
  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
    links:
      - guacd
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.entrypoints=websecure"
      - "traefik.http.routers.guacamole.middlewares=guacamole-whitelist"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.${DOMAIN_NAME}`)"
      - "traefik.http.routers.guacamole.tls.certresolver=mydnschallenge"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.middlewares.guacamole-whitelist.ipwhitelist.sourcerange=${IP_WHITELIST}"
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=${MYSQL_HOST}
      - MYSQL_DATABASE=guacamole
      - MYSQL_PORT=3306
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - GUACAMOLE_HOME=/guacamole
    image: guacamole/guacamole
    volumes:
      - ${DOCKER_DIR}/guacamole:/guacamole
    restart: always
  guacd:
    hostname: guacd
    container_name: guacd
    image: guacamole/guacd
    networks:
      - default
    restart: always
#endregion
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
