Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.network "private_network", ip: "10.0.120.10"
  config.vm.hostname = "#{ENV['CURRENT_SERVICE']}.deb"
  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.galaxy_role_file = "#{ENV['CURRENT_SERVICE']}/provision/requirements.yml"
    ansible.playbook = "#{ENV['CURRENT_SERVICE']}/provision/main.yml"
  end
end
