# traefik - Main proxy server, this the goods kids.
version: "3"
services:
  traefik:
    hostname: traefik
    image: traefik:v2.0
    container_name: traefik
    restart: always
    domainname: ${DOMAIN_NAME}
    networks:
      - default
      - traefik_proxy
    command:
      # Globals
      - "--log.level=ERROR"
      - "--global.sendAnonymousUsage=false"
      - "--api"
      # Docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # File provider
      - "--providers.file.directory=/etc/traefik/rules"
      - "--providers.file.watch=true"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # LetsEncrypt
      - "--certificatesresolvers.mydnschallenge.acme.email=${CLOUDFLARE_EMAIL}"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.mydnschallenge.acme.storage=/etc/traefik/acme.json"
    ports:
      - "30080:80"
      - "30443:443"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - "${DOCKER_DIR}/traefik/acme.json:/etc/traefik/acme.json"
      - "${DOCKER_DIR}/traefik/rules:/etc/traefik/rules"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # API
      - "traefik.enable=true"
      - "traefik.http.routers.traefikui.entrypoints=websecure"
      - "traefik.http.routers.traefikui.middlewares=traefikui-whitelist"
      - "traefik.http.routers.traefikui.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefikui.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.traefikui.tls.options=default"
      - "traefik.http.services.traefikui.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefikui.service=api@internal"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.middlewares.traefikui-whitelist.ipwhitelist.sourcerange=${IP_WHITELIST}"
      # Wildcard cert
      - "traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN_NAME}"
      # Global http-->https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
