Vagrant.configure("2") do |config|

  config.ssh.forward_agent = true
  config.vm.define "single-docker-host" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "single-docker-host"
    machine.vm.network "private_network", ip: "10.0.5.30"
    provisioner = Vagrant::Util::Platform.windows? ? :ansible_local : :ansible
    machine.vm.provision provisioner do |ansible|
        ansible.limit = "docker"
        ansible.groups = {
          "docker": ["single-docker-host"]
        }
        ansible.become = true
        ansible.galaxy_role_file = "requirements.yml"
        ansible.playbook = "bootstrap.yml"
    end
  end
end
