version: '2'
services:
  pyload:
    image: lscr.io/linuxserver/pyload
    container_name: pyload
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${DOCKER_DIR}/pyload/config:/config
      - ${DOCKER_DIR}/pyload/downloads:/downloads
    ports:
      - 8520:8000
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped