Vagrant.configure("2") do |config|

  config.ssh.forward_agent = true
  config.vm.define "zentyal" do |machine|
    machine.vm.box = "ubuntu/focal64"
    machine.vm.hostname = "zentyal"
    machine.vm.network "private_network", ip: "10.0.5.30"
    # provisioner = Vagrant::Util::Platform.windows? ? :ansible_local : :ansible
    # machine.vm.provision provisioner do |ansible|
    #     ansible.limit = "all"
    #     ansible.become = true
    #     # ansible.galaxy_role_file = "requirements.yml"
    #     ansible.playbook = "bootstrap.yml"
    # end
  end
end
