Vagrant.configure("2") do |config|
    config.vm.define "development-serve" do |machine|
      machine.vm.box = "ubuntu/bionic64"
      machine.vm.hostname = "development-server"
      machine.vm.network "private_network", ip: "10.0.1.30"
      provisioner = Vagrant::Util::Platform.windows? ? :ansible_local : :ansible
      machine.vm.provision provisioner do |ansible|
          ansible.limit = "all"
          ansible.become = true
          ansible.playbook = "bootstrap.yml"
      end
    end
  end
  