version: "2"
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    container_name: jenkins
    restart: always
    ports:
      - "5885:8080"
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DIR}/jenkins_home/data:/jenkins_home