version: "3"
services:
  #region huginn - iftt thingy
  huginn:
    image: huginn/huginn
    container_name: huginn
    restart: unless-stopped
    networks:
      - database
    environment:
      - DATABASE_ADAPTER=postgresql
      - DATABASE_RECONNECT=true
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=huginn
      - DATABASE_PASSWORD=${HUGINN_DB_PASS}
      - DATABASE_HOST=${HUGINN_DB_HOST}
      - DATABASE_PORT=5432
      - DO_NOT_CREATE_DATABASE=1
    ports:
      - "3000:3000"
  #endregion
networks:
  database:
    external:
      name: database
