version: '2'
services:
  firefly:
    image: jc5x/firefly-iii:latest
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.entrypoints=websecure"
      - "traefik.http.routers.firefly.rule=Host(`budget.${DOMAIN_NAME}`)"
      - "traefik.http.routers.firefly.tls.certresolver=mydnschallenge"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.firefly.headers.customrequestheaders.sslProxyHeaders=https"
      - "traefik.docker.network=traefik_proxy"
    environment:
      - APP_KEY
      - DB_HOST
      - DB_PASSWORD
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAMESPACE}
      - DB_USERNAME=${DB_NAMESPACE}
      - DB_CONNECTION=mysql
      - APP_URL=https://budget.${DOMAIN_NAME}
      - TRUSTED_PROXIES=**
    volumes:
      - ${DOCKER_DIR}/firefly/export:/var/www/firefly-iii/storage/export
      - ${DOCKER_DIR}/firefly/upload:/var/www/firefly-iii/storage/upload
networks:
  traefik_proxy:
    external:
      name: traefik_proxy