
version: "3.6"
services:
# Huggin - For IFTTT?

# osTicket - To support my own infrastructure I guess.

# Archimedes - Hedwig chat-bot, needs to be built.

# Jenkins CI - Docker powered, blue ocean, teenaged CI daydream.

# Eclipse Che - Web based IDE powered by Docker.

# OpenFaaS - Could be fun, eh?

# Wekan - Could be useful maybe?

# Pi-Hole - Should go somewhere right?

# Directory server of some kind

# Gittea - Simple git hosting, may or may not use. SSH no is working.
  # gittea:
  #   image: gitea/gitea
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.gittea.backend=gittea"
  #     - "traefik.gittea.frontend.rule=Host:gittea.${DOMAIN_NAME}"
  #     - "traefik.gittea.port=3000"
  #     - "traefik.gitteassh.backend=gitteassh"
  #     - "traefik.gitteassh.frontend.rule=Host:gitteassh.${DOMAIN_NAME}"
  #     - "traefik.gitteassh.port=22"
  #     - "traefik.docker.network=traefik_proxy"
  #   volumes:
  #     - ${DOCKER_DIR}/gittea/data:/data
  #   restart: always

# Mattermost - Chat platform, NOT WORKING! Oh wait, just linux permissions lolololol...
  mattermost:
    image: mattermost/mattermost-prod-app
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.backend=mattermost"
        - "traefik.frontend.rule=Host:mattermost.${DOMAIN_NAME}"
        - "traefik.port=8000"
        - "traefik.docker.network=traefik_proxy"
    volumes:
        - ${DOCKER_DIR}/mattermost/config:/mattermost/config:rw
        - ${DOCKER_DIR}/mattermost/data:/mattermost/data:rw
        - ${DOCKER_DIR}/mattermost/logs:/mattermost/logs:rw
        - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT_NUMBER=${POSTGRES_PORT}
      - MM_USERNAME=${POSTGRES_USER}
      - MM_PASSWORD=${POSTGRES_PASS}
      - MM_DBNAME=${POSTGRES_DB_NAME}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
