version: "3.6"
services:
# Transmission with VPN – Bittorrent Downloader
  transmission:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    # ports:
    # - "XXXX:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    labels:
      - "traefik.enable=true"
      - "traefik.backend=transmission"
      - "traefik.frontend.rule=Host:transmission.${DOMAIN_NAME}"
      - "traefik.port=9091"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/transmission-vpn:/data
      - ${DOCKER_DIR}/shared:/shared
      - ${DOCKER_DIR}/Downloads:/data/watch
      - ${DOCKER_DIR}/Downloads/completed:/data/completed
      - ${DOCKER_DIR}/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${TRANSMISSION_VPN_USERNAME}
      - OPENVPN_PASSWORD=${TRANSMISSION_VPN_PASSWORD}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}

# Radarr – Movie Download and Management
  radarr:
    image: "linuxserver/radarr"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:radarr.${DOMAIN_NAME}"
      - "traefik.port=7878"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - ${DOCKER_DIR}/radarr:/config
      - ${DOCKER_DIR}/Downloads/completed:/downloads
      - ${DOCKER_DIR}/media/movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - ${DOCKER_DIR}/shared:/shared
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Sonarr – TV Show Download and Management
  sonarr:
    image: "linuxserver/sonarr"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.frontend.rule=Host:sonarr.${DOMAIN_NAME}"
      - "traefik.port=8989"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - ${DOCKER_DIR}/sonarr:/config
      - ${DOCKER_DIR}/Downloads/completed:/downloads
      - ${DOCKER_DIR}/media/tvshows:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - ${DOCKER_DIR}/shared:/shared
    # ports:
    #     - "XXXX:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Lidarr - Music Download and Management
  lidarr:
    image: "linuxserver/lidarr"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lidarr"
      - "traefik.frontend.rule=Host:lidarr.${DOMAIN_NAME}"
      - "traefik.port=8686"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - ${DOCKER_DIR}/lidarr:/config
      - ${DOCKER_DIR}/Downloads:/downloads
      - ${DOCKER_DIR}/media/music:/music
      - "/etc/localtime:/etc/localtime:ro"
      - ${DOCKER_DIR}/shared:/shared
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Mylar - Comic book downloader

# Lazy Librarian - eBook downloader

# Plex Media Server - Enough said I think
  plexms:
    restart: always
    image: plexinc/pms-docker
    volumes:
      - ${DOCKER_DIR}/plexms:/config
      - ${DOCKER_DIR}/Downloads/plex_tmp:/transcode
      - ${DOCKER_DIR}/media/media:/media
      - ${DOCKER_DIR}/shared:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="claim-YYYYYYYYY"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP="http://SERVER-IP:32400/"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plexms"
      - "traefik.frontend.rule=Host:plex.${DOMAIN_NAME}"
      - "traefik.port=32400"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_proxy"
    # deploy:
    #   placement:
    #     constraints: [] #some constraint

# Tautulli (aka PlexPy) – Monitoring Plex Usage
  tautulli:
    restart: always
    image: linuxserver/tautulli
    labels:
      - "traefik.enable=true"
      - "traefik.backend=tautulli"
      - "traefik.frontend.rule=Host:tautulli.${DOMAIN_NAME}"
      - "traefik.port=8181"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - ${DOCKER_DIR}/tautulli/config:/config
      - ${DOCKER_DIR}/tautulli/logs:/logs:ro
      - ${DOCKER_DIR}/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Ombi – Accept Requests for your Media Server
  ombi:
    restart: always
    image: linuxserver/ombi
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:ombi.${DOMAIN_NAME}"
      - "traefik.port=3579"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - ${DOCKER_DIR}/ombi:/config
      - ${DOCKER_DIR}/shared:/shared
    # ports:
    #   - "XXXX:3579"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Jackett – Torrent Proxy
  jackett:
    image: "linuxserver/jackett"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.frontend.rule=Host:jackett.${DOMAIN_NAME}"
      - "traefik.port=9117"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - ${DOCKER_DIR}/jackett:/config
      - ${DOCKER_DIR}/Downloads/completed:/downloads
      - "/etc/localtime:/etc/localtime:ro"
      - ${DOCKER_DIR}/shared:/shared
    # ports:
    #   - "XXXX:9117"
    restart: always
    environment:
      - PUID=${MMOST_PUID}
      - PGID=${MMOST_PGID}
      - TZ=${TZ}
