version: '3'
services:
  gossa:
    image: pldubouilh/gossa
    container_name: gossa
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${DOCKER_DIR}:/shared
    ports:
      - 38001:8001
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped