http:
  # Add the router
  routers:
    code-server-router:
      tls:
        certresolver: mydnschallenge
      entryPoints:
        - websecure
      middlewares:
        - "code-server-whitelist"
      service: code-server-service
      rule: Host(`code.linghome.net`)

  # Add the middleware
  middlewares:
    code-server-whitelist:
      ipWhiteList:
        sourceRange:
          - "someip"

  # Add the service
  services:
    code-server-service:
      loadBalancer:
        servers:
          - url: "someurl"
