version: '2.1'
services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud
    restart: always
    ports:
      - 8950:8080
    networks:
      - default
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=${MARIADB_PASS}
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - ${DOCKER_DIR}/owncloud/data:/mnt/data

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    networks:
      - database
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASS}
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=${MARIADB_PASS}
      - MYSQL_DATABASE=owncloud
    volumes:
      - ${DOCKER_DIR}/owncloud/mariadb:/var/lib/mysql

  redis:
    image: webhippie/redis:latest
    container_name: redis
    restart: always
    networks:
      - default
    environment:
      - REDIS_DATABASES=1
    volumes:
      - ${DOCKER_DIR}/owncloud/redis:/var/lib/redis
networks:
  database:
    external:
      name: database
