---
version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID
      - PGID
      - TZ
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ${DOCKER_WORK_DIR}/jellyfin:/config
      - ${DOCKER_MEDIA_DIR}:/data
    ports:
      - 18096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped
