apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins:2.60.3-alpine
        ports:
        - containerPort: 8080
