version: "3"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID
      - PGID
      - TZ
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - ${DOCKER_WORK_DIR}/calibre-web:/config
      - ${DOCKER_MEDIA_DIR}/calibre:/books
    ports:
      - 18083:8083
    restart: unless-stopped