version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - default
    volumes:
      - ${DOCKER_DIR}/postgres_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    networks: 
      - traefik_proxy
      - default
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: webmaster
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.rule=Host(`auth.${DOMAIN_NAME}`)"
      - "traefik.http.routers.auth.entrypoints=https"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge