version: '3'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - ${DOCKER_WORK_DIR}/sonarr:/config
      - ${DOCKER_DIR_INGEST}/completed:/data/completed # Location of download managers output directory (See note in Application setup)
      - ${DOCKER_MEDIA_DIR}/Television:/tv
    ports:
      - "18989:8989"
    environment:
      - PUID
      - PGID
      - TZ