---
apiVersion: v1
kind: Service
metadata:
  name: ${EXTERNAL_SVC_NAME}
spec:
  type: ExternalName
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: ${EXTERNAL_PORT}
  externalName: ${EXTERNAL_IP}