---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: home-to-me
spec:
  ipWhiteList:
    sourceRange:
    {{ range $i, $ip := (ds "config").ips -}}
      - {{ (print $ip) }}
    {{ end }}