---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
spec:
  basicAuth:
    secret: basic-auth-passwd
# Gomplate template for ipWhitelist example
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: home-to-me
spec:
  ipWhiteList:
    sourceRange:
      {{ range $i, $ip := (ds "config").sourceRange -}}
        - {{ (print $ip) }}
      {{ end }}
    ipStrategy:
      excludedIps:
        {{ range $i, $ip := (ds "config").excludedIps -}}
        - {{ (print $ip) }}
        {{ end }}