additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=${CLOUDFLARE_EMAIL}"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesResolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
  - "--entrypoints.web.http.redirections.entrypoint.to=:443"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  - "--api"
  - "--accesslog=true"
  - "--log.level=ERROR"
hostNetwork: true
persistence:
  enabled: true
  path: /data
service:
  spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: ${HOME_IP}
env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: dns-token