additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=${CLOUDFLARE_EMAIL}"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesResolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
  - "--api"
  - "--accesslog=true"
  - "--log.level=ERROR"
hostNetwork: true
persistence:
  enabled: true
  path: /data
env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: dns-token