Vagrant.configure("2") do |config|

  config.ssh.forward_agent = true
  N = 2
  (0..N).each do |machine_id|
    machine_name = machine_id == N ?  "kube-manager" : "kube-worker-#{machine_id+1}"
    config.vm.define machine_name do |machine|
      machine.vm.box = "ubuntu/bionic64"
      machine.vm.hostname = machine_name
      machine.vm.network "private_network", ip: "10.0.5.#{10+machine_id}"

      if machine_id == N
        if Vagrant::Util::Platform.windows? do
          machine.vm.provision :ansible_local do |ansible|
            ansible.playbook = "bootstrap.yml"
            ansible.verbose = true
            ansible.install = true
            ansible.become = true
            ansible.limit = "all"
            ansible.inventory_path = "win_inventory"
          end
        else
          machine.vm.provision :ansible do |ansible|
            ansible.limit = "all"
            ansible.become = true
            ansible.groups = {
              "manager" => ["kube-manager"],
              "worker" => ["kube-worker-1", "kube-worker-2"],
              "manager:vars" => {
                "kube_role" => "manager"
              },
              "worker:vars" => {
                "kube_role" => "worker"
              }
            }
            ansible.playbook = "bootstrap.yml"
          end
        end
      end
    end
  end
end
