Vagrant.configure("2") do |config|
  hosts_map = {
    "managers" => ["kube-manager"],
    "workers" => ["kube-worker-1", "kube-worker-2"],
  }
  config.ssh.forward_agent = true
  N = 2
  (0..N).each do |machine_id|
    machine_name = machine_id == N ?  "kube-manager" : "kube-worker-#{machine_id+1}"
    config.vm.define machine_name do |machine|
      machine.vm.box = "ubuntu/bionic64"
      machine.vm.hostname = machine_name
      machine.vm.network "private_network", ip: "10.0.5.#{10+machine_id}"
      machine.vm.provision "shell" do |s|
        s.inline = <<-SHELL
          sudo cp /vagrant/sshd_config /etc/ssh/sshd_config
          sudo service sshd restart
        SHELL
      end
      
      if machine_id == N
        machine.vm.provision "shell" do |s|
          s.inline = <<-SHELL
            sudo mkdir /etc/ansible
            sudo cp /vagrant/ansible.cfg /etc/ansible/ansible.cfg
          SHELL
        end
        if Vagrant::Util::Platform.windows?
          machine.vm.provision :ansible_local do |ansible|
            ansible.playbook = "bootstrap.yml"
            ansible.install = true
            ansible.become = true
            ansible.limit = "all"
            ansible.inventory_path = "win_inventory"
            ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
          end
        else
          machine.vm.provision :ansible do |ansible|
            ansible.limit = "all"
            ansible.become = true
            ansible.groups = hosts_map
            ansible.playbook = "bootstrap.yml"
          end
        end
      end
    end
  end
end
