version: '3'
services:

#region Development Services
# Huggin - For IFTTT?

# osTicket - To support my own infrastructure I guess.

# Archimedes - Hedwig chat-bot, needs to be built.

# Jenkins CI - Docker powered, blue ocean, teenaged CI daydream.

# Eclipse Che - Web based IDE powered by Docker.

# OpenFaaS - Could be fun, eh?

# Wekan - Could be useful maybe?

#endregion

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
