version: '3'
services:

#region Game Services
# Left 4 Dead 2

# TF2

# Garry's Mod

# Minecraft

# Terraria

# Starbound

#endregion

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
